version: '3.8'

services:
  # FIWARE WireCloud Dashboard
  wirecloud:
    image: fiware/wirecloud:1.3.1
    container_name: fiware-wirecloud
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    environment:
      - WIRECLOUD_POSTGRES_HOST=postgres-db
      - WIRECLOUD_POSTGRES_PASSWORD=wirecloud
      - DJANGO_SETTINGS_MODULE=wirecloud.settings
      - WIRECLOUD_ELASTICSEARCH_URL=http://elasticsearch:9200/
    networks:
      - fiware-network

  # PostgreSQL for WireCloud
  postgres-db:
    image: postgres:13
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=wirecloud
      - POSTGRES_USER=wirecloud
      - POSTGRES_DB=wirecloud
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fiware-network

  # Elasticsearch for WireCloud
  elasticsearch:
    image: elasticsearch:2.4
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - fiware-network

  # Orion Context Broker
  orion:
    image: fiware/orion:3.8.0
    container_name: fiware-orion
    depends_on:
      - mongo-db
    ports:
      - "1026:1026"
    command: -dbhost mongo-db -logLevel DEBUG
    networks:
      - fiware-network

  # MongoDB for Orion
  mongo-db:
    image: mongo:4.4
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - fiware-network

  # IoT Device Simulator
  iot-simulator:
    build:
      context: ./simulator
      dockerfile: Dockerfile
    container_name: iot-simulator
    restart: unless-stopped
    environment:
      - ORION_URL=http://orion:1026
    depends_on:
      - orion
    networks:
      - fiware-network

  # Smart Warehouse Management Application
  warehouse-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-warehouse-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_ORION_URL=http://orion:1026
      - NEXT_PUBLIC_WIRECLOUD_URL=http://localhost:8000
    depends_on:
      - orion
      - wirecloud
    networks:
      - fiware-network

networks:
  fiware-network:
    driver: bridge

volumes:
  mongo-data:
  postgres-data:
  elasticsearch-data:

